"Змінює Спрайти":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/*.png'

"Змінює Мапи":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/**/*.yml'
    - 'Resources/Prototypes/Maps/**/*.yml'

"Змінює Інтерфейс":
- changed-files:
  - any-glob-to-any-file: '**/*.xaml*'

"Змінює Шейдери":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

"Змінює Аудіо":
- changed-files:
  - any-glob-to-any-file: '**/*.ogg'

"Без змін C#":
- changed-files:
  # Equiv to any-glob-to-all as long as this has one matcher. If ALL changed files are not C# files, then apply label.
  - all-globs-to-all-files: "!**/*.cs"
