# riot
- type: entity
  parent: [RMCHelmetBase, RMCFoldableHelmetBase]
  id: ArmorHelmetRiot
  name: протибунтівний шолом
  description: Цей шолом створений спеціально для захисту від ближніх атак. Захищає вуха.
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Head/Helmets/riot.rsi
  - type: Clothing
    sprite: _RMC14/Objects/Clothing/Head/Helmets/riot.rsi
  - type: CMArmor
    melee: 30
    bullet: 10
    # armor_laser = 10
    # armor_energy = 10
    # armor_internaldamage = 25
  - type: CMHardArmor

- type: entity
  parent: ArmorHelmetRiot
  id: ArmorHelmetRiotOld
  description: Пошарпаний протибунтівний шолом, увесь у павутинні. Досі захищає вуха.
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Head/Helmets/old_riot.rsi
    layers:
    - state: icon
  - type: Clothing
    sprite: _RMC14/Objects/Clothing/Head/Helmets/old_riot.rsi
    equipDelay: 2
    unequipDelay: 2

# basic
- type: entity
  parent: [RMCHelmetBase, RMCFoldableHelmetBase]
  id: RMCArmorHelmetSecurity
  name: шолом
  description: Стандартне екіпарування охорони. Захищає голову від ударів.
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Head/Helmets/security.rsi
  - type: Clothing
    sprite: _RMC14/Objects/Clothing/Head/Helmets/security.rsi
  - type: CMArmor
    melee: 20
    bullet: 15
    # armor_laser = 10
    # armor_energy = 10
    # armor_internaldamage = 20
