contact_links:
  - name: Повідомити про безпекову вразливість
    url: https://github.com/space-wizards/space-station-14/blob/master/SECURITY.md
    about: Повідомлення про будь-які безпекові проблеми. Звертайтеся до Візардів (офіційних розробників СС14) та краще не розголошуйте проблему публічно.
  - name: Запропонувати зміни
    url: https://discord.gg/qKNsBbV22F
    about: Якщо хочете запропонувати чи повноцінно обговорити якусь зміну – ласкаво просимо у ДС Січі (https://discord.gg/qKNsBbV22F)!
