- type: job
  parent: RMCCLFMedic
  id: SichCLFMedic
  startingGear: SichGearCLFMedic
  spawnMenuRoleName: ФВК Медик
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillMeleeWeapons: 1
        RMCSkillPolice: 1
        RMCSkillEndurance: 1
        RMCSkillJtac: 1
        RMCSkillVehicles: 1
        RMCSkillConstruction: 1
        RMCSkillEngineer: 1

        RMCSkillMedical: 2
        RMCSkillSurgery: 2
  hidden: true

- type: entity
  id: SichRandomHumanoidCLFMedic
  name: ФВК спавнер ролі привидів Медика
  suffix: Spawner, Player
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Accessory/Armbands/clf_armband.rsi
    state: icon
  - type: RandomHumanoidSpawner
    settings: SichCLFMedic

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: SichCLFMedic
  components:
  - type: GhostRole
    name: rmc-ghost-role-clf-medic
    description: rmc-ghost-role-information-clf-description
    rules: rmc-ghost-role-information-clf-rules
    reregister: false
    job: SichCLFMedic
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: CMJobHospitalCorpsman
      time: 18000 # 5 Hours
  - type: GhostRoleApplySpecial
    squad: SquadCLF

- type: startingGear
  id: SichGearCLFMedic
  equipment:
    mask: RMCCombatUtilityKnifeA
    ears: RMCHeadsetDistressCLF
    eyes: RMCGlassesMedicalHUDGlasses
    head: CMHeadBandRed
    jumpsuit: RMCJumpsuitCLFWebbingSurgical
    outerClothing: SichCoatMilitiaVest
    gloves: CMHandsBlackMarine
    shoes: RMCShoesBrown
    id: RMCIDCardCLFMedic
    belt: CMBeltMedicalFilled
    back: RMCSatchelLightpack
    pocket1: RMCFlashlight
    pocket2: RMCPouchMagazineLarge
  inhand:
  - WeaponSMGMAC15  # TODO RMC14 - Make randomized
  storage:
    back:
    - RMCGrenadeIED
    - RMCGrenadeMolotov
    - RMCGrenadeMolotov
    - CMAdvFirstAidKitFilled
    - RMCPacketGrenadeSmokeFilled
    - RMCMRECLF
    - CMCrowbar
    - RMCBinocularsCiv
    - RMCFlashlightPen
    pocket2:
    - RMCMagazineSMGMAC15Ext
    - RMCMagazineSMGMAC15Ext
    - RMCMagazineSMGMAC15Ext
    - RMCMagazineSMGMAC15Ext
    belt:
    - CMDefibrillator
    - CMHealthAnalyzer
    - CMRollerBedSpawnFolded
    - CMEpinephrineAutoInjector
    - CMEpinephrineAutoInjector
    - CMBloodPackFull
    - CMBloodPackFull
    outerClothing:
    - RMCMagazineSMGMAC15
    - RMCMagazineSMGMAC15
