# Всеодно поки використовуватися не буде. Не завершено.
- type: job
  parent: RMCCLFCellCommander
  id: SichCLFCellCommander
  startingGear: SichGearCLFCellCommander
  spawnMenuRoleName: ФВК Командир Ячейки
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillFireman: 3
        RMCSkillMeleeWeapons: 1
        RMCSkillPolice: 1 # RMC14 disallow use of flashbangs
        RMCSkillEndurance: 5
        RMCSkillJtac: 4
        RMCSkillVehicles: 1

        RMCSkillConstruction: 2
        RMCSkillEngineer: 2
        RMCSkillPowerLoader: 2
        RMCSkillMedical: 2
        RMCSkillSurgery: 1

        RMCSkillOverwatch: 1
        RMCSkillLeadership: 3
        RMCSkillCqc: 2

        RMCSkillSmartGun: 1
        RMCSkillExecution: 1
  hidden: true

- type: entity
  id: SichRandomHumanoidCLFCellCommander
  name: ФВК спавнер ролі привидів командира Ячейки
  suffix: Spawner, Player
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Accessory/Armbands/clf_armband.rsi
    state: icon
  - type: RandomHumanoidSpawner
    settings: SichCLFCellCommander

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: SichCLFCellCommander
  components:
  - type: GhostRole
    name: rmc-ghost-role-clf-cell-commander
    description: rmc-ghost-role-information-clf-description
    rules: rmc-ghost-role-information-clf-rules
    reregister: false
    job: SichCLFCellCommander
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: CMJobSquadLeader
      time: 36000 # 10 Hours
  - type: GhostRoleApplySpecial
    squad: SquadCLF

- type: startingGear
  id: SichGearCLFCellCommander
  equipment:
    head: RMCArmorHelmetMercenaryMiner
    mask: RMCCombatUtilityKnifeB
    ears: RMCHeadsetDistressCLF
    jumpsuit: RMCJumpsuitCLFSoldier
    outerClothing: SichCoatMilitiaHarness
    gloves: CMHandsBlackMarine
    shoes: RMCShoesCombat
    suitstorage: RMCSmartGunCLF
    id: RMCIDCardCLFCellCommander # TODO RMC14
    belt: RMCBeltSmartGunOperatorPistolCLF
    pocket1: RMCPouchSurvivalFill
    pocket2: RMCPouchFirstAidInjectors
  storage:
    outerClothing:
    - RMCSpeedLoaderMatebaHighImpact
    - RMCSpeedLoaderMatebaHighImpact
