- type: job
  parent: RMCCLFEngineer
  id: SichCLFEngineer
  startingGear: SichGearCLFEngineer
  spawnMenuRoleName: ФВК Інженер
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillMeleeWeapons: 1
        RMCSkillPolice: 1
        RMCSkillEndurance: 1
        RMCSkillJtac: 1
        RMCSkillVehicles: 1
        RMCSkillMedical: 1

        RMCSkillConstruction: 2
        RMCSkillEngineer: 2
        RMCSkillPowerLoader: 2
  hidden: true

- type: entity
  id: SichRandomHumanoidCLFEngineer
  name: ФВК спавнер ролі привидів Інженера
  suffix: Spawner, Player
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Accessory/Armbands/clf_armband.rsi
    state: icon
  - type: RandomHumanoidSpawner
    settings: SichCLFEngineer

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: SichCLFEngineer
  components:
  - type: GhostRole
    name: rmc-ghost-role-clf-engineer
    description: rmc-ghost-role-information-clf-description
    rules: rmc-ghost-role-information-clf-rules
    reregister: false
    job: SichCLFEngineer
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: CMJobCombatTech
      time: 18000 # 5 Hours
  - type: GhostRoleApplySpecial
    squad: SquadCLF

- type: startingGear
  id: SichGearCLFEngineer
  equipment:
    head: RMCHelmetWelding
    mask: RMCCombatUtilityKnifeA
    ears: RMCHeadsetDistressCLF
    eyes: ClothingEyesGlassesMeson # ТОДО. Замінити на РМСні
    jumpsuit: RMCJumpsuitCLFWebbingMAR50
    outerClothing: SichCoatMilitiaHauberk
    gloves: CMHandsInsulated
    shoes: RMCShoesBrown
    id: RMCIDCardCLFEngineer
    belt: CMBeltUtilityFilled
    back: RMCSatchelLightpackWelder
    pocket1: RMCPouchConstructionFillLowGrade
    pocket2: RMCPouchFirstAidERTFill
  inhand:
  - WeaponShotgunM357Sawn # TODO RMC14 - Make randomized
  - CMShellShotgunIncendiaryBuckshot # TODO RMC14 - Make randomized
  storage:
    jumpsuit:
    - CMShellShotgunBuckshot
    - CMShellShotgunBuckshot
    - CMShellShotgunBuckshot
    - CMShellShotgunBuckshot
    - CMShellShotgunBuckshot
    back:
    - RMCExplosiveBreachingCharge
    - RMCExplosiveBreachingCharge
    - RMCGrenadeMolotov
    - RMCGrenadeMolotov
    - RMCBinocularsCiv
    - RMCMRECLF
    - RMCFlashlight
    - RMCBoxClaymoreMineFilled
    - RMCBoxClaymoreMineFilled
    belt:
    - RMCExplosivePlastic
    - RMCExplosivePlastic
    - RMCExplosivePlastic
    outerClothing:
    - CMShellShotgunFlechette
    - CMShellShotgunFlechette
