- type: job
  parent: RMCCLFSpecialist
  id: SichCLFSpecialist
  startingGear: SichGearCLFSpecialist
  spawnMenuRoleName: ФВК Спеціаліст
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillMeleeWeapons: 1
        RMCSkillPolice: 1
        RMCSkillEndurance: 1
        RMCSkillVehicles: 1
        RMCSkillConstruction: 1
        RMCSkillEngineer: 1

        RMCSkillJtac: 2
        RMCSkillCqc: 1
        RMCSkillLeadership: 1
  hidden: true

- type: entity
  id: SichRandomHumanoidCLFSpecialist
  name: ФВК спавнер ролі привидів Спеціаліста
  suffix: Spawner, Player
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Accessory/Armbands/clf_armband.rsi
    state: icon
  - type: RandomHumanoidSpawner
    settings: SichCLFSpecialist

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: SichCLFSpecialist
  components:
  - type: GhostRole
    name: rmc-ghost-role-clf-specialist
    description: rmc-ghost-role-information-clf-description
    rules: rmc-ghost-role-information-clf-rules
    reregister: false
    job: SichCLFSpecialist
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: CMJobWeaponsSpecialist
      time: 18000 # 5 Hours
  - type: GhostRoleApplySpecial
    squad: SquadCLF

- type: startingGear
  id: SichGearCLFSpecialist
  equipment:
    head: RMCHeadMilitiaBucket
    mask: RMCCombatUtilityKnifeA
    ears: RMCHeadsetDistressCLF
    eyes: RMCGlassesM4SPRBattleSight
    jumpsuit: RMCJumpsuitCLFWebbingMAR50
    outerClothing: SichCoatMilitia
    gloves: CMHandsBlackMarine
    shoes: RMCShoesBrown
    id: RMCIDCardCLFSpecialist
    belt: RMCMK80BeltFilled
    back: RMCSatchelLightpack
    suitstorage: RMCWeaponMar50LMG
    pocket1: RMCPouchExplosiveFilledC4SPP
    pocket2: RMCPouchFirstAidERTFill
  inhand:
  - RMCEarmuffs
  storage:
    jumpsuit:
    - CMCrowbar
    - RMCMRECLF
    - RMCBinoculars
    - RMCGrenadeMolotov
    - RMCGrenadeMolotov
    back:
    - RMCBoxClaymoreMineFilled
    - CMPacketGrenadeFragOldFilled
    - CMPacketGrenadeFragOldFilled
    - RMCWeaponLauncherDisposableFolded
    - RMCMagazineMar50LMG
    - RMCMagazineMar50LMG
    outerClothing:
    - RMCMagazineMar50LMG
    - RMCMagazineMar50LMG
    - RMCMagazineMar50LMG
    pocket1:
    - RMCExplosivePlastic
    - RMCExplosivePlastic
